version: "2"

services:
  visioedu: 
    container_name: visioedu
    build: .
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.visioedu.rule=Host(`visioedu.inf.ufsm.br`)"
      - "traefik.http.routers.visioedu.entrypoints=web"
      - "traefik.docker.network=traefik"
    networks:
      - traefik
      - default
    ports: 
      - "8081:8081"
    depends_on:
      - mysql
  mysql:
    container_name: visioedu_db
    build: ./scripts
    networks:
      - default
    ports:
      - 3307:3306 
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: visioedupsw2019
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--skip-character-set-client-handshake','--default-authentication-plugin=mysql_native_password']
networks:
  traefik:
    external:
      name: traefik    
