setwd("C:/Users/gabri/Documents/Projetos/PSW2/microdados_ed_basica_2018/DADOS/ESCOLAS/")
dfEscolas <- read.csv('ESCOLAS.CSV', sep = '|', header = TRUE)
View(dfEscolas)
filter <- c('CO_ENTIDADE', 'NO_ENTIDADE', 'TP_SITUACAO_FUNCIONAMENTO', 'CO_REGIAO', 'CO_UF', 'CO_MUNICIPIO', 'TP_DEPENDENCIA', 'TP_LOCALIZACAO', 'IN_AGUA_FILTRADA', 'IN_AGUA_INEXISTENTE', 'IN_ESGOTO_INEXISTENTE', 'IN_ENERGIA_INEXISTENTE', 'IN_LIXO_RECICLA', 'IN_LIXO_COLETA_PERIODICA', 'IN_LABORATORIO_INFORMATICA', 'IN_SALA_ATENDIMENTO_ESPECIAL', 'IN_LABORATORIO_CIENCIAS', 'IN_BIBLIOTECA', 'IN_SALA_LEITURA', 'IN_BIBLIOTECA_SALA_LEITURA','QT_SALAS_EXISTENTES', 'QT_SALAS_UTILIZADAS', 'IN_EQUIP_RETROPROJETOR', 'IN_EQUIP_MULTIMIDIA', 'QT_COMP_ALUNO', 'IN_INTERNET', 'IN_BANDA_LARGA', 'QT_FUNCIONARIOS', 'TP_AEE', 'TP_LOCALIZACAO_DIFERENCIADA')
dfFiltrado <- dfEscolas[, filter]
View(dfFiltrado)
write.csv(dfFiltrado, 'ESCOLAS_FILTRADO.csv', row.names = F)
